import { addProductRepository,bestSellerRepository,findProductIdRepository,findProductsByIdsRepository,listProductRepository, removeProductRepository, totalProductCount, allProductRepository, relatedProductRepository } from "../repository/productRepository.js";
import orderModel from "../schema/orderModel.js";
import productModel from "../schema/productModel.js";
import userModel from "../schema/userModel.js";
import inventoryLedgerModel from "../schema/inventoryLedgerModel.js";


export const addProductService = async ({
  name,
  description,
  price,
  category,
  subcategory,
  bestseller,
  sizes,
  files,
  quantity,
}) => {
    const imageUrl = files.map((file)=> file.path);
    
    //Sending the data to the repository layer....
    const product = await addProductRepository({name,description,price,category,subcategory,bestseller,sizes,imageUrl,quantity});
    
    // Add ledger entries for initial stock
    if (product.sizes && product.sizes.length > 0) {
      const ledgerEntries = product.sizes.map(sizeObj => ({
        productId: product._id,
        referenceId: product._id,
        variantSize: sizeObj.size,
        quantityChanged: sizeObj.quantity,
        reason: 'Initial Stock',
        notes: 'Added during product creation',
      }));
      await inventoryLedgerModel.insertMany(ledgerEntries);
    }

    return product;
};

const checkUserCanReview = async (userId, productId) => {
    if (!userId || !productId) {
        return false;
    }
    const deliveredOrders = await orderModel.find({
        userId,
        status: { $regex: /^delivered$/i }
    });

    const targetId = String(productId);
    return deliveredOrders.some(order =>
        Array.isArray(order.items) && order.items.some(item => {
            // 1. Check dedicated productId field (new orders going forward)
            if (item.productId && String(item.productId) === targetId) return true;
            // 2. Check item._id (may be auto-generated by Mongoose but worth trying)
            if (item._id && String(item._id) === targetId) return true;
            // 3. Scan all string/object fields of the item that could hold the product ID
            //    (covers COD orders where the full product object was sent from frontend)
            return Object.values(item.toObject ? item.toObject() : item).some(val =>
                val && typeof val === 'string' && val === targetId
            );
        })
    );
};

export const reviewProductService = async (userId, productId, star, reviewText, action) => {
    // 1. Check if user ordered the product and it is delivered.
    const canReview = await checkUserCanReview(userId, productId);
    if (!canReview) {
        throw { status: 403, message: "You can only review products that have been delivered to you." };
    }
    
    const user = await userModel.findById(userId);
    const product = await productModel.findById(productId);
    
    if (!product) throw { status: 404, message: "Product not found" };

    if (action === 'delete') {
        product.reviews = product.reviews.filter(r => r.userId !== userId);
        product.markModified('reviews');
        await product.save();
        return { message: "Review deleted successfully", data: product.reviews };
    }

    // It's a create or update
    const existingReviewIndex = product.reviews.findIndex(r => r.userId === userId);
    
    const reviewData = {
        userId,
        name: user.name,
        star,
        reviewText,
        time: Date.now()
    };

    if (existingReviewIndex !== -1) {
        // Update existing review
        product.reviews[existingReviewIndex] = reviewData; //if already exist then update it...
    } else {
        // Post new review
        product.reviews.push(reviewData); //if new then add it...
    }
    
    product.markModified('reviews');
    await product.save();

    return { message: "Review posted successfully", data: product.reviews, canReview: true };
};

export const listproductService = async(page, limit, skip, filter = {})=>{
    const responselist = await listProductRepository(page, limit, skip, filter);
    return responselist;
}

export const removeProductService = async(id)=>{
    const product = await findProductIdRepository(id);

    if (!product) {
        throw { status: 404, message: "Product with provided id not found" };
    }

    const response = await removeProductRepository(id);
    return response;
}

export const singeProductService = async(id, userId)=>{
    const product = await findProductIdRepository(id);
    if (!product) {
        throw { status: 404, message: "Product not found" };
    }
    
    const canReview = await checkUserCanReview(userId, id);
    
    return { product, canReview };
}

export const bestSellerService = async()=>{
    const response = await bestSellerRepository();
    const bestseller = response.slice(0,5).reverse();
    return bestseller;
}

export const latestCollectionService = async()=>{
    const productList = await listProductRepository();
    const latestProductList = productList.slice(0,10);
    return latestProductList;
}

export const updateProductStatusService = async (id, status) => {
    const product = await productModel.findById(id);
    if (!product) throw { status: 404, message: "Product not found" };
    product.status = status;
    await product.save();
    return product;
};

export const getAdminProductStatsService = async (productId) => {
    // 1. Get the total number of orders that contain this product
    // 2. Calculate the total revenue generated by this product
    const orders = await orderModel.find({ "items._id": productId });
    
    let totalRevenue = 0;
    let totalOrders = orders.length;

    orders.forEach(order => {
        order.items.forEach(item => {
            if (item._id.toString() === productId.toString()) {
                totalRevenue += (item.price * item.quantity);
            }
        });
    });

    return { totalOrders, totalRevenue };
};

export const getBulkProductsService = async (ids) => {
    if (!ids || !Array.isArray(ids) || ids.length === 0) {
        return [];
    }
    const products = await findProductsByIdsRepository(ids);
    return products;
}

export const relatedProductService = async(category, subcategory) =>{
    const response = await relatedProductRepository(category, subcategory);
    return response;
}

//till not used
export const allProductService = async()=>{
    const response= await allProductRepository();
    return response;
}